version: 2

sources:
  - name: cr_db_landing
    database: cr_db
    schema: public
    tables: 
    - name: landing_battle_info
    - name: landing_cards
    - name: landing_clans
    - name: landing_members
    - name: landing_opp_cards_battle_log
    - name: landing_player_cards
    - name: landing_player_cards_battle_log
    - name: landing_player_support_card
    - name: landing_players
    - name: landing_support_cards