name: "clash_royale_analytics"
version: "1.0.0"
config-version: 2

profile: "clash_royale_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
models:
  clash_royale_analytics:
    +materialized: view
    
    dim:
      +materialized: table
    
    fct:
      +materialized: table
